# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_text', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleccion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.Indicador')),
            ],
        ),
    ]
